spring.application.name=lab7_673380301_0_sec1

# Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/lab7
spring.datasource.username=postgres
spring.datasource.password=Tanny007

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# For PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
